/**
 * Public avatar icons via DiceBear (no API key).
 * Seed is deterministic from the subscription name so the same name always
 * gets the same icon without user upload/selection.
 *
 * @see https://www.dicebear.com/styles/
 */

export type SubscriptionIconKind = "sub" | "collection";

const DICEBEAR_VERSION = "9.x";

/** Styles that look good at small list avatar sizes. */
const STYLE_BY_KIND: Record<SubscriptionIconKind, string> = {
  sub: "shapes",
  collection: "rings",
};

/**
 * Build a DiceBear SVG URL for a subscription / collection.
 * Empty seed falls back to a stable default.
 */
export function buildSubscriptionIconUrl(
  seed: string,
  kind: SubscriptionIconKind = "sub",
): string {
  const safeSeed = (seed || "subscription").trim() || "subscription";
  const style = STYLE_BY_KIND[kind] || STYLE_BY_KIND.sub;
  const params = new URLSearchParams({
    seed: safeSeed,
    // Slightly more color without looking noisy at 40–56px
    backgroundType: "gradientLinear",
  });
  return `https://api.dicebear.com/${DICEBEAR_VERSION}/${style}/svg?${params.toString()}`;
}

/**
 * Assign an auto icon when the value is empty, or when `force` is true.
 * Returns the (possibly unchanged) icon URL.
 */
export function ensureSubscriptionIcon(
  currentIcon: string | undefined | null,
  seed: string,
  kind: SubscriptionIconKind = "sub",
  force = false,
): string {
  const existing = (currentIcon || "").trim();
  if (existing && !force) return existing;
  return buildSubscriptionIconUrl(seed, kind);
}

/** True if the icon looks like one we auto-generated (DiceBear). */
export function isAutoGeneratedIcon(icon: string | undefined | null): boolean {
  if (!icon) return false;
  return icon.includes("api.dicebear.com");
}
